// #define TAP_CODE_DELAY 50
// #define TAPPING_TERM 200
// #define HOLD_ON_OTHER_KEY_PRESS
// #define TAPPING_FORCE_HOLD
// #define QUICK_TAP_TERM 0

#pragma once

#define VIAL_KEYBOARD_UID {0xDD, 0x07, 0xF7, 0xCA, 0x81, 0x76, 0x55, 0x68}

#define VIAL_UNLOCK_COMBO_ROWS {1, 2}
#define VIAL_UNLOCK_COMBO_COLS {2, 2}

#define DYNAMIC_KEYMAP_LAYER_COUNT 6

#define DOUBLE_TAP_SHIFT_TURNS_ON_CAPS_WORD
